feat: [MSSQL] expose storage encryption
cloudfoundry/csb-brokerpak-aws pull request #1044
Opened 2023-08-03 17:52 UTC by fnaranjo-vmw

[#185149632]

### Checklist:

* [ ] Have you added Release Notes in the docs repositories?
* [x] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

2023-08-04 13:30 UTC, pivotal-marcela-campo requested changes

2023-08-04 16:13 UTC, fnaranjo-vmw commented on terraform-tests/mssql_test.go
> +		When("an invalid kms_key_id is passed and storage_encrypted is true", func() {
Yes! Great catch. Thanks.

2023-08-04 16:15 UTC, fnaranjo-vmw commented on terraform/mssql/provision/validations.tf
> +resource "terraform_data" "kms_key_was_not_provided" {
You are absolutely right.
Removing. Great catch.

Thanks for noticing.
I wasn't aware or completely forgot about such default behaviour.
I agree forcing customers to specify the AWS managed key ARN is not nice.

2023-08-04 16:26 UTC, fnaranjo-vmw commented on terraform-tests/mssql_test.go
> +		When("an invalid kms_key_id is passed and storage_encrypted is true", func() {
Sorry, nop. It is a legitimate test with wrong copy-pasted title.
I'll fix it.

2023-08-04 16:48 UTC, fnaranjo-vmw commented on terraform-tests/mssql_test.go
> +		When("an invalid kms_key_id is passed and storage_encrypted is true", func() {
Fixed the description.

2023-08-07 09:16 UTC, pivotal-marcela-campo approved these changes

2023-08-07 09:16 UTC, pivotal-marcela-campo commented on aws-mssql.yml
> +    validations: terraform/mssql/provision/validations.tf
praise: love it

2023-08-07 09:16 UTC, pivotal-marcela-campo commented on terraform-tests/mssql_test.go
> +			// Currently, this tests the exact same inputs as the one `with default values`
suggestion: Interesting take, maybe we can discuss in tech forum and see if we want to make this the standard.

2023-08-07 09:46 UTC, merged