Binding tf provider mssql 185151996
cloudfoundry/csb-brokerpak-aws pull request #1085
Opened 2023-08-15 16:24 UTC by zucchinidev

### Checklist:

* [ ] Have you added Release Notes in the docs repositories?
* [x] Have you ran `make run-integration-tests` and `make run-terraform-tests`?
* [x] Have you ran acceptance tests for the service under change?
* [x] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

2023-08-16 10:58 UTC, pivotal-marcela-campo requested changes

2023-08-16 10:58 UTC, pivotal-marcela-campo commented on providers/terraform-provider-csbsqlserver/connector/connector_suite_test.go
> +	session := testhelpers.StartServer(adminPassword, port)
This StartServer set up creates a database. So strictly speaking we are only testing that we can connect and create bindings when the database is already there. We are missing testing the scenario when the database has not yet been created.

2023-08-16 11:05 UTC, pivotal-marcela-campo commented on providers/terraform-provider-csbsqlserver/connector/connector_suite_test.go
> +	session := testhelpers.StartServer(adminPassword, port)
Discussed with @zucchinidev and agreed to provide the tests in a separate pull request to unblock other tasks. The scanario missing is tested with acceptance tests as well and those pass, so we have confidence this works.

2023-08-16 11:05 UTC, pivotal-marcela-campo approved these changes

2023-08-16 11:08 UTC, merged

2023-08-23 13:16 UTC, fnaranjo-vmw commented on providers/terraform-provider-csbsqlserver/go.mod
> +	github.com/pborman/uuid v1.2.1
We might want to replace this with `https://github.com/google/uuid`

2023-08-23 13:21 UTC, fnaranjo-vmw commented on providers/terraform-provider-csbsqlserver/go.mod
> +	github.com/maxbrunsfeld/counterfeiter/v6 v6.6.2
I believe we are not using this package.
According to counterfeiter documentation, for it to do anything we need to [add go:generate directives](https://github.com/maxbrunsfeld/counterfeiter/#step-2a---add-gogenerate-directives). 
What makes me think that we don't need it for this project.
I have searched for "go:generate

2023-08-23 13:26 UTC, fnaranjo-vmw commented on providers/terraform-provider-csbsqlserver/go.mod
> +	github.com/denisenkom/go-mssqldb v0.12.3
Do we want to favour Microsoft's fork of this module?
https://github.com/microsoft/go-mssqldb

It seems to be currently more active and I would expect it to have more strict collaboration guidelines and better security audits (although that's not necessarily true).

2023-08-23 14:17 UTC, fnaranjo-vmw commented
Created a PR to replace the modules mentioned in my comments:
https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1106